import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robertkuhar' at '8/14/16 5:37 PM' with Gradle 2.14.1
 *
 * @author robertkuhar, @date 8/14/16 5:37 PM
 */
public class Library {
    private static final Logger LOGGER = LoggerFactory.getLogger(Library.class);

    public boolean someLibraryMethod() {
        LOGGER.trace("someLibraryMethod()");
        return true;
    }
}
