version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies and setting up environment..."
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # - apt-get update
      # - apt-get install -y jq 
      # - wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      # - tar xzvf apache-maven-3.9.4-bin.tar.gz
      # - ln -s apache-maven-3.9.4 maven
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package 
  post_build:
    commands:
      - echo "Build completed on $(date)"
      
artifacts:
  files:
    - target/*.war
