- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: "{{ workspace_path }}/webapp/target/webapp.war"
    dest_path: "/opt/tomcat/webapps/"
    config_file_src_path: "{{ hosts }}-config.yaml"
    config_file_dest_path: "/home"
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansible
        group: ansible
        mode: 0644

